### ISSUE TITLE
PgCodec problems

### ISSUE THREAD

**Issue by schmitch** [finagle/finagle-postgres#11]
Hello, I currently get the following error against PostgreSQL 9.4 while using finangle and finatra

```
java.lang.AbstractMethodError: com.twitter.finagle.postgres.codec.PgCodec$$anon$1.newClientDispatcher(Lcom/twitter/finagle/transport/Transport;Lcom/twitter/finagle/Stack$Params;)Lcom/twitter/finagle/Service;
    at com.twitter.finagle.builder.CodecClient$Client$3.newDispatcher(ClientBuilder.scala:1121)
    at com.twitter.finagle.client.StdStackClient$$anon$1$$anonfun$make$1$$anonfun$apply$1.apply(StackClient.scala:343)
    at com.twitter.finagle.client.StdStackClient$$anon$1$$anonfun$make$1$$anonfun$apply$1.apply(StackClient.scala:343)
    at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:947)
    at com.twitter.util.Try$.apply(Try.scala:13)
    at com.twitter.util.Future$.apply(Future.scala:102)
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:947)
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:947)
    at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:893)
    at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:892)
    at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:100)
    at com.twitter.util.Promise$Transformer.k(Promise.scala:100)
    at com.twitter.util.Promise$Transformer.apply(Promise.scala:110)
    at com.twitter.util.Promise$Transformer.apply(Promise.scala:91)
    at com.twitter.util.Promise$$anon$3.run(Promise.scala:691)
    at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:187)
    at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
    at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:216)
    at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:84)
    at com.twitter.util.Promise.continue(Promise.scala:689)
    at com.twitter.util.Promise$Chained.continue(Promise.scala:206)
    at com.twitter.util.Promise$Responder$class.transform(Promise.scala:175)
    at com.twitter.util.Promise$Chained.transform(Promise.scala:182)
    at com.twitter.util.Future.flatMap(Future.scala:892)
    at com.twitter.util.Future.map(Future.scala:947)
    at com.twitter.finagle.client.StdStackClient$$anon$1$$anonfun$make$1.apply(StackClient.scala:343)
    at com.twitter.finagle.client.StdStackClient$$anon$1$$anonfun$make$1.apply(StackClient.scala:343)
    at com.twitter.finagle.ServiceFactory$$anon$9.apply(Service.scala:206)
    at com.twitter.finagle.postgres.codec.HandleErrorsProxy.apply(PgCodec.scala:80)
    at com.twitter.finagle.postgres.codec.AuthenticationProxy.apply(PgCodec.scala:107)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.builder.CodecClient$$anon$4$$anon$2.apply(ClientBuilder.scala:1071)
    at com.twitter.finagle.service.FailFastFactory.apply(FailFastFactory.scala:183)
    at com.twitter.finagle.pool.WatermarkPool.apply(WatermarkPool.scala:136)
    at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:84)
    at com.twitter.finagle.service.FailureAccrualFactory.apply(FailureAccrualFactory.scala:140)
    at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:84)
    at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:84)
    at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:84)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:239)
    at com.twitter.finagle.loadbalancer.HeapBalancer.apply(HeapBalancer.scala:252)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:239)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.factory.StatsFactoryWrapper.apply(StatsFactoryWrapper.scala:43)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.factory.RefcountedFactory.apply(RefcountedFactory.scala:19)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.factory.TimeoutFactory.apply(TimeoutFactory.scala:58)
    at com.twitter.finagle.service.Requeues$$anon$2$$anon$1.com$twitter$finagle$service$Requeues$$anon$$anon$$applySelf(Requeues.scala:50)
    at com.twitter.finagle.service.Requeues$$anon$2$$anon$1.apply(Requeues.scala:74)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:239)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.factory.TimeoutFactory.apply(TimeoutFactory.scala:58)
    at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:84)
    at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:84)
    at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:84)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:239)
    at com.twitter.finagle.ProxyServiceFactory$class.apply(Service.scala:214)
    at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:239)
    at com.twitter.finagle.ServiceFactory.apply(Service.scala:149)
    at com.twitter.finagle.FactoryToService.apply(Service.scala:313)
    at com.twitter.finagle.postgres.Client.fire(Client.scala:127)
    at com.twitter.finagle.postgres.Client.send(Client.scala:135)
    at com.twitter.finagle.postgres.Client.sendQuery(Client.scala:75)
    at com.twitter.finagle.postgres.Client.executeUpdate(Client.scala:43)
    at de.envisia.hello.HelloWorldServer.warmup(HelloWorldServer.scala:22)
    at com.twitter.inject.app.App$class.main(App.scala:51)
    at de.envisia.hello.HelloWorldServer.com$twitter$inject$server$TwitterServer$$super$main(HelloWorldServer.scala:13)
    at com.twitter.inject.server.TwitterServer$class.main(TwitterServer.scala:33)
    at de.envisia.hello.HelloWorldServer.main(HelloWorldServer.scala:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:167)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:166)
    at scala.Option.foreach(Option.scala:257)
    at com.twitter.app.App$class.nonExitingMain(App.scala:166)
    at de.envisia.hello.HelloWorldServer.nonExitingMain(HelloWorldServer.scala:13)
    at com.twitter.app.App$class.main(App.scala:132)
    at de.envisia.hello.HelloWorldServer.main(HelloWorldServer.scala:13)
    at de.envisia.hello.HelloWorldServerMain.main(HelloWorldServer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sbt.Run.invokeMain(Run.scala:67)
    at sbt.Run.run0(Run.scala:61)
    at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
    at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Logger$$anon$4.apply(Logger.scala:85)
    at sbt.TrapExit$App.run(TrapExit.scala:248)
    at java.lang.Thread.run(Thread.java:745)
Exception thrown in main on startup

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 2 s, completed 24.05.2015 20:48:30

Process finished with exit code 1
```

The error appears to happen ON ALL query types, correct or incorrect ones.

Oh and Integration Tests are running fine, looks like some dependency problems.
But the only different thing is finangle 6.24 and 6.25, however that shouldn't be too incompatible.

Looks like the following pull request will fix the issue: #6

**Comment by clhodapp** [comment]
Should this be closed, given that https://github.com/finagle/finagle-postgres/pull/15 (referenced in https://github.com/finagle/finagle-postgres/pull/6) was merged?
