### ISSUE TITLE
Unknown command complete response tag TRUNCATE TABLE

### ISSUE THREAD

**Issue by d-s-d** [finagle/finagle-postgres#124]
When issuing a TRUNCATE TABLE command the response from the server is not properly parsed and an exception is thrown:
```
java.lang.IllegalStateException: Unknown command complete response tag TRUNCATE TABLE
	at com.twitter.finagle.postgres.messages.BackendMessageParser.parseTag(BackendMessageParser.scala:245)
	at com.twitter.finagle.postgres.messages.BackendMessageParser.parseC(BackendMessageParser.scala:218)
	at com.twitter.finagle.postgres.messages.BackendMessageParser.parse(BackendMessageParser.scala:30)
```

Observed with version `0.10.0`

**Comment by vic** [comment]
Same happens when trying to execute a `SET TRANSACTION ISOLATION LEVEL` command

https://github.com/getquill/quill/issues/29#issuecomment-560162692
