### ISSUE TITLE
java.lang.NoSuchMethodError: com.twitter.finagle.client.Transporter$SocksProxy$.param()Lcom/twitter/finagle/Stack$Param;

### ISSUE THREAD

**Issue by FunkyYang** [finagle/finagle-postgres#87]
I meet a problem with finagle-postgres lib
finatra-http:18.10.0
finagle-core: 18.10.0
finagle-postgres:18.10.0

```
class P2PAnalysisServiceTest extends FeatureTest {

  override val server = new EmbeddedHttpServer(new P2PService)

  val domainKey = "1"
  val appKey = "1"
  val date = "20180103"
  val start = "20180810"
  val end = "20180817"
  val hour = 14

  test("P2PAnalysisService#perform feature") {
    server.httpGet(
      path = s"service/play/count/day/${domainKey}/${appKey}?date=${date}",
      andExpect = Ok
    )
  }
}
```

system stack
```
An exception or error caused a run to abort: java.lang.NoSuchMethodError: com.twitter.finagle.client.Transporter$SocksProxy$.param()Lcom/twitter/finagle/Stack$Param; 
java.lang.Exception: java.lang.NoSuchMethodError: com.twitter.finagle.client.Transporter$SocksProxy$.param()Lcom/twitter/finagle/Stack$Param;
	at com.twitter.inject.server.EmbeddedTwitterServer.$anonfun$runNonExitingMain$1(EmbeddedTwitterServer.scala:434)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at com.twitter.util.Try$.apply(Try.scala:26)
	at com.twitter.util.ExecutorServiceFuturePool$$anon$4.run(FuturePool.scala:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.twitter.finagle.client.Transporter$SocksProxy$.param()Lcom/twitter/finagle/Stack$Param;
```

and this code is throw the stack
```
object PostgresModule extends TwitterModule with Logging {

  val postgresConn: Flag[String] = flag("postgres",
    "jdbc:postgresql://xxx:xxx/xxxx?stringtype=unspecified",
    "the connection url string for postgres")

  @Singleton
  @Provides
  def postgresClient: PostgresClient = {
    val url = postgresConn().substring(5)
    val uri = URI.create(url)
    val host = uri.getHost
    val port = uri.getPort

    val client = Postgres.Client().withCredentials("postgres", Some("postgres"))
      .database("xxx").withSessionPool.maxSize(5)
      .withBinaryResults(true).withBinaryParams(true).newRichClient(s"$host:$port")

    client
  }

  override def singletonShutdown(injector: Injector): Unit = {
    super.singletonShutdown(injector)
    debug("====singletonShutdown====")
    injector.instance[PostgresClient].close()
  }

  override def singletonStartup(injector: Injector): Unit = {
    debug("=====singletonStartup=====")
    super.singletonStartup(injector)
  }
}
```

**Comment by FunkyYang** [comment]
oh I put finagle-netty3_2.12 in and fix this issue
